version: "3.8"
services:
  radar-api:
    build: .
    # Watch for updated source code
    command: [ "npm", "run", "dev:watch" ]
    depends_on:
      - postgresql
    env_file:
      - .env
    ports:
      - "3001:3001"
    # Mount source directory
    # `npm install` needs to run to install dependencies
    volumes:
      - "./:/usr/src/app"
  postgresql:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
