name: Docker build and push
on:
  workflow_run:
    workflows: ["Run tests"]
    branches: [main]
    types: 
      - completed
  pull_request:
    types: [ opened, synchronize ]
jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'pull_request' }}
    env:
      APPLICATION: radar-api
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.CONTAINER_REGISTRY }}
          username: ${{ secrets.SERVICE_PRINCIPAL }}
          password: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}
      - name: Docker build and push
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: |
          env

          tag=latest

          docker build . -t ${{ secrets.CONTAINER_REGISTRY }}/${APPLICATION}:${{ github.sha }}
          docker push ${{ secrets.CONTAINER_REGISTRY }}/${APPLICATION}:${{ github.sha }}
          docker tag ${{ secrets.CONTAINER_REGISTRY }}/${APPLICATION}:${{ github.sha }} ${{ secrets.CONTAINER_REGISTRY }}/${APPLICATION}:${tag}
          docker push ${{ secrets.CONTAINER_REGISTRY }}/${APPLICATION}:${tag}
      - name: Docker build and push (Pull Request)
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          env

          tag=${GITHUB_HEAD_REF/\//-}
          tag=${tag:0:10}
          tag=${tag%-}
          
          docker build . -t ${{ secrets.CONTAINER_REGISTRY }}/${APPLICATION}:${{ github.sha }}
          docker push ${{ secrets.CONTAINER_REGISTRY }}/${APPLICATION}:${{ github.sha }}
          docker tag ${{ secrets.CONTAINER_REGISTRY }}/${APPLICATION}:${{ github.sha }} ${{ secrets.CONTAINER_REGISTRY }}/${APPLICATION}:${tag}
          docker push ${{ secrets.CONTAINER_REGISTRY }}/${APPLICATION}:${tag}
