name: build
on:
  workflow_run:
    workflows: ["test"]
    branches: [main]
    types: 
      - completed
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: ACR build
        id: acr
        uses: ams0/acr-task-github-action@v2
        with:
          service_principal: ${{ secrets.service_principal }}
          service_principal_password: ${{ secrets.service_principal_password }}
          tenant: ${{ secrets.tenant }}
          # registry: ${{ secrets.registry }}
          registry: crsharedradar
          repository: radar-api
          image: radar-api
          folder: .
          dockerfile: ./Dockerfile
