name: build
on:
  workflow_run:
    workflows: ["test"]
    branches: [main]
    types: 
      - completed
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        uses: azure/docker-login@v1
        with:
          login-server: crsharedradar.azurecr.io
          username: crsharedradar
          password: 5XccmvXetau42+8dpj9U9vGfSO9UzYv3

      - run: |
          docker build . -t crsharedradar.azurecr.io/radar-api:${{ github.sha }}
          docker push crsharedradar.azurecr.io/radar-api:${{ github.sha }}
          docker push crsharedradar.azurecr.io/radar-api:latest