name: Docker build and push
on:
  workflow_run:
    workflows: ["Run tests"]
    branches: [main]
    types: 
      - completed
jobs:
  on-success:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        uses: azure/docker-login@v1
        with:
          login-server: crsharedradar.azurecr.io
          username: ${{ secrets.SERVICE_PRINCIPAL }}
          password: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}
      - run: |
          docker build . -t crsharedradar.azurecr.io/radar-api:${{ github.sha }}
          docker push crsharedradar.azurecr.io/radar-api:${{ github.sha }}
          docker tag crsharedradar.azurecr.io/radar-api:${{ github.sha }} crsharedradar.azurecr.io/radar-api:latest
          docker push crsharedradar.azurecr.io/radar-api:latest