name: Destroy pull request environment

# only trigger on pull request closed events
on:
  pull_request:
    types: [ closed ]

jobs:
  destroy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          repository: softchoice-corp/ctt-radar-terraform
          ref: pr-env
          ssh-key: ${{ secrets.GIT_CLONE_SSH_KEY }}
      - name: Destroy radar-app
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        run: |
          env=${GITHUB_HEAD_REF/\//-}
          env=${env:0:10}
          env=${env%-}

          terraform init -backend-config="storage_account_name=${{ secrets.TF_STATE_PR_STGACCT_NAME }}"  -backend-config="key=${env}-app.terraform.tfstate" -backend-config="resource_group_name=${{ secrets.TF_STATE_PR_RG_NAME }}"
          terraform destroy -var-file=env/pr.tfvars -var "env=${env}" -var "app_service_radar-api_docker_tag=${env}" -var "app_service_radar-client_docker_tag=${env}" -auto-approve
        working-directory: ./terraform/radar-app
      - name: Destroy radar-support
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        run: |
          env=${GITHUB_HEAD_REF/\//-}
          env=${env:0:10}
          env=${env%-}

          terraform init -backend-config="storage_account_name=${{ secrets.TF_STATE_PR_STGACCT_NAME }}"  -backend-config="key=${env}-support.terraform.tfstate" -backend-config="resource_group_name=${{ secrets.TF_STATE_PR_RG_NAME }}"
          terraform destroy -var-file=env/pr.tfvars -var "oauth_google_key=${{ secrets.OAUTH_GOOGLE_KEY }}" -var "oauth_google_secret=${{ secrets.OAUTH_GOOGLE_SECRET }}" -var "postgresql_administrator_password=P@ssw0rd1234" -var "env=${env}" -auto-approve
        working-directory: ./terraform/radar-support