name: Deploy pull request environment

# only trigger on pull request closed events
on:
  pull_request:
    types: [ opened, edited, synchronize]
    # Maybe should just be opened as it is just for CD. Terraform does not need to run again.
    # Maybe label to trigger reploy as a hack
    # types: [ opened ]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          repository: softchoice-corp/ctt-radar-terraform
          ref: pr-env
          # NOTE: PAT was not working
          # token: ${{ secrets.CLONE_PERSONAL_ACCESS_TOKEN }}
          ssh-key: ${{ secrets.GIT_CLONE_SSH_KEY }}
      - run: ls -lR
      - run: terraform version
      - run: az version
      - shell: bash
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        run: |
          env=${GITHUB_HEAD_REF/\//-}
          env=${env:0:10}
          env=${env%-}

          pushd ./terraform/radar-support
          terraform init -backend-config="storage_account_name=${{ secrets.TF_STATE_PR_STGACCT_NAME }}"  -backend-config="key=${env}-support.terraform.tfstate" -backend-config="resource_group_name=${{ secrets.TF_STATE_PR_RG_NAME }}"
          terraform plan -var-file=env/pr.tfvars -var "oauth_google_key=${{ secrets.OAUTH_GOOGLE_KEY }}" -var "oauth_google_secret=${{ secrets.OAUTH_GOOGLE_SECRET }}" -var "postgresql_administrator_password=P@ssw0rd1234" -var "env=${env}"
          popd

          # Set var for tag