name: Deploy pull request environment

# only trigger on pull request closed events
on:
  pull_request:
    types: [ opened ]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v2
        with:
          repository: github.com:softchoice-corp/ctt-radar-terraform
      - run: ls -lR
      - run: terraform version
      - run: az version
# DUMMY LINE      
