name: Deploy pull request environment

# only trigger on pull request closed events
on:
  pull_request:
    types: [ opened ]

jobs:
  build:
    env:
      APPLICATION: radar-api
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.CONTAINER_REGISTRY }}
          username: ${{ secrets.SERVICE_PRINCIPAL }}
          password: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}
      - run: |
          env=${GITHUB_HEAD_REF/\//-}
          env=${env:0:10}
          env=${env%-}

          docker build . -t ${{ secrets.CONTAINER_REGISTRY }}/${APPLICATION}:${{ github.sha }}
          docker push ${{ secrets.CONTAINER_REGISTRY }}/${APPLICATION}:${{ github.sha }}
          docker tag ${{ secrets.CONTAINER_REGISTRY }}/${APPLICATION}:${{ github.sha }} ${{ secrets.CONTAINER_REGISTRY }}/${APPLICATION}:${env}
          docker push ${{ secrets.CONTAINER_REGISTRY }}/${APPLICATION}:${env}
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          repository: softchoice-corp/ctt-radar-terraform
          ref: main
          # NOTE: PAT was not working
          # token: ${{ secrets.CLONE_PERSONAL_ACCESS_TOKEN }}
          ssh-key: ${{ secrets.GIT_CLONE_SSH_KEY }}
      - run: ls -lR
      - run: terraform version
      - run: az version
      - name: Deploy radar-support
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        run: |
          env=${GITHUB_HEAD_REF/\//-}
          env=${env:0:10}
          env=${env%-}

          terraform init -backend-config="storage_account_name=${{ secrets.TF_STATE_PR_STGACCT_NAME }}"  -backend-config="key=${env}-support.terraform.tfstate" -backend-config="resource_group_name=${{ secrets.TF_STATE_PR_RG_NAME }}"
          terraform apply -var-file=env/pr.tfvars -var "oauth_google_key=${{ secrets.OAUTH_GOOGLE_KEY }}" -var "oauth_google_secret=${{ secrets.OAUTH_GOOGLE_SECRET }}" -var "postgresql_administrator_password=P@ssw0rd1234" -var "env=${env}" -auto-approve
        working-directory: ./terraform/radar-support
      - name: Deploy radar-app
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        run: |
          az login --service-principal --username ${{ secrets.ARM_CLIENT_ID }} --password ${{ secrets.ARM_CLIENT_SECRET }} --tenant ${{ secrets.ARM_TENANT_ID }}

          env=${GITHUB_HEAD_REF/\//-}
          env=${env:0:10}
          env=${env%-}

          terraform init -backend-config="storage_account_name=${{ secrets.TF_STATE_PR_STGACCT_NAME }}"  -backend-config="key=${env}-app.terraform.tfstate" -backend-config="resource_group_name=${{ secrets.TF_STATE_PR_RG_NAME }}"
          terraform apply -var-file=env/pr.tfvars -var "env=${env}" -var "app_service_radar-api_docker_tag=${env}" -var "app_service_radar-client_docker_tag=latest" -auto-approve
        working-directory: ./terraform/radar-app
      # TODO - Google OAUTH call back url creation